ARG SCALA_VERSION=3.3.5
ARG SBT_VERSION=1.10.10
ARG JAVA_VERSION=graalvm-community-21.0.2

FROM sbtscala/scala-sbt:${JAVA_VERSION}_${SBT_VERSION}_${SCALA_VERSION}

WORKDIR /app

# Copier les fichiers nécessaires
COPY ./app /app




